services:
  couchdb:
    environment:
      COUCHDB_USER: "${COUCHDB_USER}"
      COUCHDB_PASSWORD: "${COUCHDB_PASS}"
    image: couchdb
    volumes:
      - ./data/couchdb:/opt/couchdb/data
    ports:
      - 127.0.0.1:5984:5984
    restart: unless-stopped

  haproxy:
    environment:
      DOMAIN: "${DOMAIN}"
    image: haproxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/etc/haproxy:/usr/local/etc/haproxy:ro
      - ./data/etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped

  nginx:
    environment:
      DOMAIN: "${DOMAIN}"
    image: nginx
    expose:
      - "81"
    volumes:
      - ./data/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/deploy/web:/home/deploy/web:ro
    restart: unless-stopped
