services:
  couchdb:
    environment:
      COUCHDB_USER: "${COUCHDB_USER}"
      COUCHDB_PASSWORD: "${COUCHDB_PASS}"
    image: couchdb
    volumes:
      - ./data/couchdb:/opt/couchdb/data
    ports:
      - 127.0.0.1:5984:5984
    restart: unless-stopped

  haproxy:
    environment:
      DOMAIN: "${DOMAIN}"
      COUCHDB_PATH: "${COUCHDB_PATH}"
    image: haproxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/etc/haproxy:/usr/local/etc/haproxy:ro
      - ./data/etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
#    entrypoint: /bin/sh -c "
#      cp /usr/local/etc/haproxy/haproxy.cfg /tmp/haproxy.cfg &&
#      echo \"sed -i \"s#COUCHDB_PATH#${COUCHDB_PATH}#g\" &&
#      sed -i \"s#COUCHDB_PATH#${COUCHDB_PATH}#g\" /tmp/haproxy.cfg &&
#      exec haproxy -f /tmp/haproxy.cfg"

  nginx:
    environment:
      DOMAIN: "${DOMAIN}"
    image: nginx
    expose:
      - "81"
    volumes:
      - ./data/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/deploy/web:/home/deploy/web:ro
    restart: unless-stopped
